server:
  port: 8082

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - info
          - health
          - metrics
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true